### ISSUE TITLE
create a template for new format requests

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/object-formats#1]
Create an issue template for new format requests. This should include all of the fields for a format, plus a checklist to be sure they have not created a duplicate, etc.

**Comment by mbjones** [comment]
Began a new issue template for formats. Needs review. Example of usage in issue #3.

**Comment by twhiteaker** [comment]
I exercised the new format template today in #12.  The last checkbox is 

> - [ ] All extensions in widespread use are listed

But I thought we could only list one extension.  Or, do we list all the extensions (in the Format Metadata section), and only the most commonly used one actually shows up in the pull request?

**Comment by twhiteaker** [comment]
In the Format Metadata section, instead of a bulleted list, how about the actual XML snippet?  This would enable the submitter to copy/paste the entire section from the format list XML document, and thus save some typing.

**Comment by twhiteaker** [comment]
In the template, there's an extra space between `mediaType` and the following colon.

**Comment by mbjones** [comment]
@twhiteaker I considered using XML for the metadata snippet, and I see the advantages. But thought it best to leave it in the more accessible markdown so that folks that aren't as familiar with the XML structure can still suggest new formats. Whomever creates the PR would presumably be familiar enough to convert quickly. Does that sound ok to you?

**Comment by twhiteaker** [comment]
Yep, sounds good.
