### ISSUE TITLE
GeoTIFF

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#12]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `image/geotiff`
- formatName: `GeoTIFF`
- formatType: `DATA`
- mediaType : `image/tiff`
- extension: `tiff`

Being a raster GIS format, the GeoTIFF may have other files that go with it such as pyramids or metadata files. Therefore, a zip version is also provided.

- formatId: `image/geotiff+zip`
- formatName: `GeoTIFF (zipped)`
- formatType: `DATA`
- mediaType : `image/tiff+zip`
- extension: `zip`

# Format description

*Describe why a new format is needed, including items such as where the format type has been encountered, what software produces it, and what software can read it.*

GeoTIFF is a TIFF image with embedded georeferencing information such that the pixels of the image can be correctly located in a map in a geographic information system (GIS).  This public domain metadata standard is a good choice for sharing raster GIS data, as most GIS software supports and can generate files using this format.  There are numerous examples of GeoTIFFs archived in DataONE nodes.

This is one of the formats recommended by an EDI/LTER working group developing best practices for archiving spatial data.

# Specification / Namespace documentation

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

* Standard: http://docs.opengeospatial.org/is/19-008r4/19-008r4.html

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format Name includes version info where applicable
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format
- [x] All extensions in widespread use are listed

**Comment by twhiteaker** [comment]
I'm struggling with the question of versions.  I believe the current OGC standard is at 1.1.  But I don't recall ever seeing what version of GeoTIFF I'm working with or what version is produced by software.  It just produces it.  This is a bit different from my experience with EML or netCDF-CF, in which the metadata creator is more in tune with version number.

So, at what point is including the version number useful, versus just leading to unnecessary bloat in the format list?

**Comment by mbjones** [comment]
Good question, @twhiteaker. It seems to me that we should register separate versions if typically those files require different software or code processes to handle the format. If, for all intents and purposes, nobody cares which version of a spec is used, then we can probably ignore it as well. But if they need to use different software or different algorithms to process incompatible versions of the format, then we would probably want to be more specific. Open to suggestions on how to draw this distinction, but I think this kind of practicality should be an important consideration.

Otherwise, the proposed formats look good to me.

**Comment by mbjones** [comment]
So @twhiteaker and others -- are you happy with the current proposal as reflected in the description above? And does the associated PR incorporate any needed changes? If so, and if there are no objections, we can probably merge this to develop in prep for release. Last call for comments.

**Comment by twhiteaker** [comment]
Looks good to me as is.

**Comment by csjx** [comment]
Looks good to me too 👍. 

With regard to versions, we have other formats that are also a "catch all" that represents every version of a format, and the un-versioned `image/geotiff` format could act as that as well.  If in the future someone realizes that we need to track specific versions of the GeoTIFF format like `image/geotiff-1.0.0`, we can do so without too much trouble.  But as Matt said, if we know ahead of time that software processing is version-dependent, it's best to get the versions encoded from the get go.

**Comment by mbjones** [comment]
Merged #13, GeoTIFF ready to be included.
