### ISSUE TITLE
GeoPackage

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#14]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `application/geopackage+sqlite3`
- formatName: `GeoPackage Encoding Standard (OGC) Format Family`
- formatType: `DATA`
- mediaType: `application/geopackage+sqlite3`
- extension: `gpkg`

# Format description

*Describe why a new format is needed, including items such as where the format type has been encountered, what software produces it, and what software can read it.*

This is one of the formats recommended by an EDI/LTER working group developing best practices for archiving spatial data.  It is an OGC encoding standard for storing geospatial vector and raster data.  Geographic Information System (GIS) software such as ArcGIS and QGIS can read and write it.

# Specification / Namespace documentation

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

* Website: https://www.geopackage.org/
* OGC standard: https://www.ogc.org/standards/geopackage
* Where I got the name, extension, and media type: https://www.digipres.org/formats/sources/fdd/formats/#fdd000520

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [ ] Format Name includes version info where applicable
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format
- [x] All extensions in widespread use are listed

# Considerations

The [GeoPackage website](https://www.geopackage.org/) lists `application/geopackage+vnd.sqlite3` as the media type and points to IANA, but IANA has `application/geopackage+sqlite3` which is what I used for this proposal.

I wasn't sure if I should include the version.  It looks like OGC is at 1.2.1.  I skirted around the version issue by including `Format Family` in the name.  

I also included `OGC` in the name, following the [Library of Congress Example](https://www.digipres.org/formats/sources/fdd/formats/#fdd000520).

**Comment by mbjones** [comment]
GeoPackage 1.3.0 was released in Feb 2021 and is more or less backwards compatible with 1.2.1. Release notes are here: https://docs.ogc.org/is/12-128r17/18-066r1.html  Because the version info is embedded in the GeoPackage data, software should be easily able to deal with version differences in the format spec, and so it seems to me that a single formatId for the family is a reasonable way to go. So I think this approach would work fine as @twhiteaker proposed.

Also, the 1.3.0 specification clarified the registered mime type:

> GeoPackage now has a registered media type (formerly MIME type) of application/geopackage+sqlite3 [B27]. Previous statements that the media type is application/geopackage+vnd.sqlite3 are in error.

So I think this is ready to go with a PR.

**Comment by mbjones** [comment]
Merged PR #32 into develop, will be reviewed with other changes for milestone 1.26.

**Comment by mbjones** [comment]
Closed, awaiting release in PR #35.
