### ISSUE TITLE
Esri File Geodatabase

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#15]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `application/vnd.gdb+zip`
- formatName: `Esri File Geodatabase (zipped)`
- formatType: `DATA`
- mediaType: `application/vnd.gdb+zip`
- extension: `zip'

# Format description

*Describe why a new format is needed, including items such as where the format type has been encountered, what software produces it, and what software can read it.*

This format is a zipped Esri file geodatabase.  When unzipped, a file geodatabase is a folder whose contents comprise a file based geodatabase.  The folder must have the .gdb extension at the end of its name.  

The format can store both vector and raster geospatial data.  Geographic Information System (GIS) software such as ArcGIS and QGIS can read/write this format.  However, reading/writing is quite limited outside of ArcGIS.

This is one of the formats that is somewhat recommended by an EDI/LTER working group developing best practices for archiving spatial data.  We prefer more open formats.  However, due to the utility of file geodatabases and ubiquity of ArcGIS, we suspect many folks are storing geospatial data in this format.  This format provides features not available in other geospatial format, and so export to a more open format sometimes means losing/obscuring data or functionality.

# Specification / Namespace documentation

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

About: https://desktop.arcgis.com/en/arcmap/10.3/manage-data/administer-file-gdbs/file-geodatabases.htm
API for read/write: https://github.com/Esri/file-geodatabase-api

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [ ] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format Name includes version info where applicable
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format
- [x] All extensions in widespread use are listed

# Considerations

I used the `vnd.xxx+zip` pattern from the shapefile example.  Someone please vet this.

**Comment by mbjones** [comment]
@twhiteaker I looked at your proposal to use zip for gdb, and I agree with the approach. I implemented this in PR #34, and will merge to develop shortly for review of the proposed changes shortly.

**Comment by mbjones** [comment]
Closed, awaiting release in PR #35.
