### ISSUE TITLE
CF 1.5-1.8+

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#17]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

1.5:

- formatId: `CF-1.5`
- formatName: `NetCDF Climate and Forecast Metadata Convention, version 1.5`
- formatType: `DATA`
- mediaType: `application/netcdf`
- extension: `nc`

1.6:

- formatId: `CF-1.6`
- formatName: `NetCDF Climate and Forecast Metadata Convention, version 1.6`
- formatType: `DATA`
- mediaType: `application/netcdf`
- extension: `nc`

1.7:

- formatId: `CF-1.7`
- formatName: `NetCDF Climate and Forecast Metadata Convention, version 1.7`
- formatType: `DATA`
- mediaType: `application/netcdf`
- extension: `nc`

1.8 and up:

- formatId: `netCDF-CF`
- formatName: `NetCDF Climate and Forecast Metadata Convention`
- formatType: `DATA`
- mediaType: `application/netcdf`
- extension: `nc`

# Format description

*Describe why a new format is needed, including items such as where the format type has been encountered, what software produces it, and what software can read it.*

CF 1.5 through 1.8 are released.  Since we have 1.0 through 1.4, we should add the rest.  Starting with CF 1.8, a `Conventions` attribute indicating the convention used is required (previously it was optional) in the netCDF file, and so indicating that this is a CF file via formatName is enough, and you can leave it up to CF-aware software to interpret the version upon inspecting the file itself.

# Specification / Namespace documentation

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

http://cfconventions.org/

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

# Considerations

*Describe or list any considerations that might impact the use of the format, or related issues that we should consider.*

The `1.8 and up` entry does not indicate in the format name that this is for 1.8 and up.  Will this be confusing to users who are trying to choose a formatName?  I was trying to be efficient and save future work with the generic `1.8 and up` version, but I also have no guarantee that CF won't drop the conventions-identification requirement in the future (though I am almost certain they would not drop it).

Stepping back a bit, I question whether the CF Conventions entries are even needed.  I think when choosing a format, specifying nteCDF would be enough.  Software that can read netCDF files, is either CF-aware or not.  If aware, it will know what to do with the file when it sees it.  If not, the end user may have to hold the software's hand a bit.  But either way, I don't see how knowing whether CF is used ahead of time, is helpful.

**Comment by mbjones** [comment]
These look great @twhiteaker . I'd like to hear from others whether they think having separate formatIds for each of the CF versions is useful, or whether your proposal that all that is needed is to know it is a NetCDF file. I think the original logic was to be able to help software know that it would have to deal with different CF conventions, but that may indeed be overkill. Nevertheless, we never remove existing formats from the vocabulary that could have been used in some system. But we certainly don't have to continue all of the version-specific ones if we prefer a generic `netcdf` format. Let's get input from @datadavev @csjx @jclark @laijasmine @amoeba and others on their houghts on this.

**Comment by datadavev** [comment]
Flagging versions up to 1.7 then `netCDF-CF` for 1.8 onwards makes sense to me.

**Comment by mbjones** [comment]
Proposed changes implemented in PR #30 and merged into `develop`.

**Comment by mbjones** [comment]
Closed, awaiting release in PR #35.
