### ISSUE TITLE
rationale behind R Markdown file (pandoc markdown compatible)

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#18]
The only entry for R Markdown says:
R Markdown file (pandoc markdown compatible)

Why is pandoc mentioned?  If there are flavors of R Markdown that aren't pandoc compatible, then why isn't there an entry for vanilla R Markdown?  If all R Markdown files are pandoc compatible, then why not just remove the pandoc part?

**Comment by mbjones** [comment]
@csjx @jclark do either of you know why it was listed as 'pandoc markdown compatible'?

**Comment by mbjones** [comment]
ping @csjx @jeanetteclark again on this RMarkdown format question...

**Comment by csjx** [comment]
Hmm, good point. I'm not sure why that is. @jeanetteclark do you recall?

**Comment by mbjones** [comment]
My personal take on this is that there is only 1 RMarkdown syntax, and it supports various formatting directives that vary based on the processor used to convert the markdown. So, there isn't really a 'pandoc compatible' markdown, as much as markup features in markdown and RMarkdown that require certain markdown processors and flags (like citation support in pandoc, but there are many other examples like GFM, tables, and others). So, I think this should just be "R Markdown".

**Comment by mbjones** [comment]
Chnaged the markdown names as discussed. Remaining metadata like formatId are the same.
