### ISSUE TITLE
add CodeMeta format

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#19]
# Format Metadata

For 1.0:

- formatId: `https://doi.org/10.5063/schema/codemeta-1.0`
- formatName: `CodeMeta, version 1.0`
- formatType: `METADATA`
- mediaType: `application/ld+json`
- extension: `json`

For 2.0:

- formatId: `https://doi.org/10.5063/schema/codemeta-2.0`
- formatName: `CodeMeta, version 2.0`
- formatType: `METADATA`
- mediaType: `application/ld+json`
- extension: `json`

# Format description

CodeMeta includes structured metadata about software and may accompany software or scripts in a data package.

# Specification / Namespace documentation

https://codemeta.github.io/

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

# Considerations

I'm not sure if the format identifier is appropriate, or if some URL should be used such as `https://raw.githubusercontent.com/codemeta/codemeta/2.0-rc/codemeta.jsonld`.

**Comment by mbjones** [comment]
Thanks, @twhiteaker, adding CodeMeta would be great. Fully support. 

CodeMeta has well-established identifiers for each versioned namespace of the spec (I know, as I created them). So, I suggest each version of codemeta should be registered as a format, as the namespaces (and the field definitions and relationsips) change across the versions. We've had two codemeta releases to date, and expect a third sometime soon.

Also, I think the media type should be `application/ld+json`: https://www.iana.org/assignments/media-types/application/ld+json

**Comment by mbjones** [comment]
The namespaces for the two versions of CodeMeta are DOIs. From the CodeMeta site:

- CodeMeta-2.0: https://doi.org/10.5063/schema/codemeta-2.0
    - Matthew B. Jones, Carl Boettiger, Abby Cabunoc Mayes, Arfon Smith, Peter Slaughter, Kyle Niemeyer, Yolanda Gil, Martin Fenner, Krzysztof Nowak, Mark Hahnel, Luke Coy, Alice Allen, Mercè Crosas, Ashley Sands, Neil Chue Hong, Patricia Cruse, Daniel S. Katz, Carole Goble. 2017. CodeMeta: an exchange schema for software metadata. Version 2.0. KNB Data Repository. doi:10.5063/schema/codemeta-2.0
- CodeMeta-1.0: https://doi.org/10.5063/schema/codemeta-1.0
    - Matthew B. Jones, Carl Boettiger, Abby Cabunoc Mayes, Arfon Smith, Peter Slaughter, Kyle Niemeyer, Yolanda Gil, Martin Fenner, Krzysztof Nowak, Mark Hahnel, Luke Coy, Alice Allen, Mercè Crosas, Ashley Sands, Neil Chue Hong, Patricia Cruse, Daniel S. Katz, Carole Goble. 2016. CodeMeta: an exchange schema for software metadata. KNB Data Repository. doi:10.5063/schema/codemeta-1.0

I would suggest we use those two namespace URIs for the associated formatId fields, which would allow us to check the two remaining checklist boxes (id is the commony used namespace, and id has embedded version info).

@twhiteaker If you agree with this, can you modify the main proposal above to reflect these changes?

**Comment by twhiteaker** [comment]
Done

**Comment by mbjones** [comment]
Looks good to me. I will incorporate it into a PR for review.

**Comment by mbjones** [comment]
Merged into `develop`. Closing this issue, please reopen if you see issues to be addressed before the release is made.
