### ISSUE TITLE
Document how to submit new formats

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/object-formats#2]
Update the README to reflect the format proposal process.

**Comment by twhiteaker** [comment]
For pull requests, should the `develop` branch be selected as the branch to merge changes into?

**Comment by twhiteaker** [comment]
Can new entries be inserted anywhere in the list?  For example, there are entries for CF conventions up to 1.4 in the list, but one could add entries up to CF 1.8, and I think they'd belong just after the existing CF entries rather than at the end of the document.

**Comment by mbjones** [comment]
@twhiteaker yes, on the `develop` branch for pull requests.

On the issue of adding new formats, we have always appended to the end of the file rather than reordering it, but technically there's no reason one has to do it that way. It does make it easier to find new entries when they are at the end. As the list grows, a search facility on the `listFormats()` API call would probably be nice.
