### ISSUE TITLE
Create new format-id for science-on-schema.org Dataset in JSON-LD

### ISSUE THREAD

**Issue by datadavev** [DataONEorg/object-formats#21]
# Format Metadata

- formatId: `science-on-schema.org/Dataset/1.2;ld+json`
- formatName: JSON-LD metadata
- formatType: `METADATA`
- mediaType: `application/ld+json`
- extension: `jsonld`

# Format description

Dataset resources may be described by `schema.org/Dataset` markup serialized as JSON-LD in dataset landing pages. In order for DataONE to collate and index such metadata it is necessary to provide a suitable `formatId`. 

# Specification / Namespace documentation

* https://science-on-schema.org/
* https://schema.org/Dataset

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [ ] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [ ] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [ ] Format Name is recognizable and sensible
- [ ] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

# Considerations

`application/ld+json` is likely the most common serialization format, though technically any of the RDF formats may be used.

The formal definition of Dataset is at https://schema.org/Dataset though science-on-schema.org provides numerous recommendations that are necessary for effective use on science data.

Versioning is necessary as recommendations change over time.

**Comment by mbjones** [comment]
This looks good to me @datadavev . Are you happy with the formatId as proposed? Does anyone else want to weigh in on that before we create a PR?

**Comment by mbjones** [comment]
My main comment is the formatId is complicated and would likely invite typos.

**Comment by csjx** [comment]
@mbjones @datadavev - While I think it's a fairly complex `formatId` string, we have others that are not terribly memorable and prone to typos as well.  That said, it's important that we capture the type and version in the `formatId` and the `formatName`, and I think this the `formatId` does this pretty concisely.  Perhaps the `formatName` value could be `Science on Schema.org Dataset JSON-LD Metadata Version 1.2` or something a bit more verbose.  Those are the user-facing descriptions, so I think need to convey the details.

**Comment by amoeba** [comment]
I'm not sure I see why the `;ld+json` is in the formatID. Can we just have it as `science-on-schema.org/Dataset/1.2`? Otherwise I'm fine with this.

**Comment by datadavev** [comment]
Because the content can be serialized in multiple formats. This formatId is specific to the JSON-LD serialization.

**Comment by amoeba** [comment]
Ah, right. Thanks @datadavev.

**Comment by taojing2002** [comment]
I am using the format id `science-on-schema.org/Dataset/1.2;ld+json` in the metacat implemenation. If we will change it, it is better to do it right now to avoid more effort to modify code.

**Comment by taojing2002** [comment]
Removed the version from the format id:
`science-on-schema.org/Dataset;ld+json`
