### ISSUE TITLE
bash shell scripts

### ISSUE THREAD

**Issue by laijasmine** [DataONEorg/object-formats#25]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `application/x-sh`
- formatName: `Bourne shell script`
- formatType: `DATA`
- mediaType: `application/x-sh`
- extension: `.sh`

# Format description

*Describe why a new format is needed, including items such as where the format type has been encountered, what software produces it, and what software can read it.*

Shell scripts are commonly used by researchers to execute programs and manipulate files.

# Specification / Namespace documentation

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

https://tiswww.case.edu/php/chet/bash/bashtop.html

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [ ] MediaType is the most specific MIME media type that applies to the format

# Considerations

*Describe or list any considerations that might impact the use of the format, or related issues that we should consider.*

**Comment by mbjones** [comment]
This looks good @laijasmine. Thanks. Once we have a PR for the format changes, we can merge it.

**Comment by mbjones** [comment]
Merged into `develop`. Closing this issue, please reopen if you see issues to be addressed before the release is made.
