### ISSUE TITLE
Jupyter Notebooks

### ISSUE THREAD

**Issue by laijasmine** [DataONEorg/object-formats#26]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `application/x-ipynb+json`
- formatName: `Jupyter Notebook`
- formatType: `DATA`
- mediaType: `application/x-ipynb+json`
- extension: `ipynb`

# Format description

This format is commonly used by researchers to have their code and text in the same place when doing analysis. How notebooks are formatted can be found here: https://nbformat.readthedocs.io/en/latest/

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

**Comment by mbjones** [comment]
Thanks @laijasmine, looks good. We need a PR for this to proceed.

**Comment by mbjones** [comment]
Merged into `develop`. Closing this issue, please reopen if you see issues to be addressed before the release is made.
