### ISSUE TITLE
Proposed Sqlite Format ID

### ISSUE THREAD

**Issue by dvirlar2** [DataONEorg/object-formats#37]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `application/vnd.sqlite3`
- formatName: `SQLite Database`
- formatType: `DATA`
- mediaType: `application/vnd.sqlite3`
- extension: `db`

# Format description

There is no SQL Lite database format ID as of now. There is the "GeoPackage Encoding Standard (OGC) Format Family" option, but this has a format id of `geopackage+sqlite3`. This new format ID is needed for when researchers decide to archive their .db files. 

# Specification / Namespace documentation

- IANA registered format: https://www.iana.org/assignments/media-types/application/vnd.sqlite3
- SQLLite database format docs: https://www.sqlite.org/fileformat.html

# Checklist

- [X] The format is not a duplicate of another in the list under a different name or identifier
- [X] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [x] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

# Considerations

Unknown

**Comment by mbjones** [comment]
The MIME media type for sqllite is `application/vnd.sqlite3`, as registered at IANA here: https://www.iana.org/assignments/media-types/application/vnd.sqlite3  So I think we should use that for the formatId, which I've changed in the summary above.

**Comment by dvirlar2** [comment]
Yeah that sounds great! I'll make the change in my initial comment

**Comment by mbjones** [comment]
Perfect. I think this looks good as it is now, and will request review from the broader community for feedback.
