### ISSUE TITLE
Object Format List for DataONE

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/object-formats#39]
# Format Metadata

*Provide the standard metadata for the proposed format, ensuring that the id and name are unique and appropriate to the version of the format being proposed.*

- formatId: `http://ns.dataone.org/service/types/v1#ObjectFormatList`
- formatName: `Object Format List`
- formatType: `METADATA`
- mediaType: `text/xml`
- extension:`xml`

# Format description
When we install a new CN, we should insert the object which contains the list of object formats first before it functions. Currently we use the old Metacat API to insert/update it and the object is treated as a metadata object. However, after we disable the old Metacat API, we should use DataONE `cn.create` to insert the documents. If we don't have an object format identifier, which is a metadata type, for this object, CN will treat it as a data object.

# Specification / Namespace documentation
The namespace is [http://ns.dataone.org/service/types/v1]( https://github.com/DataONEorg/d1_schemas/blob/main/dataoneTypes.xsd)

*Provide the location(s) of the documentation of the format specification or the namespace for the format or vocabulary.*

# Checklist

- [x] The format is not a duplicate of another in the list under a different name or identifier
- [x] Format Identifier is unique
- [x] Format identifier is the commonly-used identifier for the namespace, or the best URI for the namespace, or the best Media type
- [ ] Format identifier is same as the MIME media type if the mime type is specific to *only* this format (e.g., `image/png` is specific to one format, whereas `text/xml` is not specific to one format)
- [x] Format Name is recognizable and sensible
- [x] Format includes version info where applicable in formatName and formatId
- [x] formatType is the correct type from the values: `DATA`, `METADATA`, or `RESOURCE`
- [x] MediaType is the most specific MIME media type that applies to the format

# Considerations

*Describe or list any considerations that might impact the use of the format, or related issues that we should consider.*

**Comment by mbjones** [comment]
@taojing2002 How about a fragmentID so the namespace resolves:

- formatId: http://ns.dataone.org/service/types/v1#ObjectFormatList

**Comment by mbjones** [comment]
I also updated the name to remove the `DataONE`, and switched to a hash symbol in the formatID.

**Comment by mbjones** [comment]
I also think the format should use DataONE V2 namespaces. So the final would be: 

- formatId: `http://ns.dataone.org/service/types/v1#ObjectFormatList`
- formatName: `Object Format List`
- formatType: `METADATA`
- mediaType: `text/xml`
- extension: `xml`
