### ISSUE TITLE
Update WaterML link in readme

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#5]
The readme states:

> ...the `formatId` for WaterML is `http://www.loc.gov/METS/`...

I think someone accidentally copied the id from the next item down in the list.

To fix it, you could just change the link in the readme to `http://www.cuahsi.org/waterML/1.0/`.

But, maybe just use a different example instead?  Now that I look at it, there may be some issues with the WaterML entries, which I'll post as a separate issue.

**Comment by mbjones** [comment]
Thanks @twhiteaker that was my error in my haste as I mentally switched from using WaterML to METS. I'll patch up the README.

**Comment by mbjones** [comment]
Updated README. Closed.
