### ISSUE TITLE
Document how to submit edits to existing formats

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#7]
You may want a separate template for this, similar to the "submit a new format" template.  You may also want a branch naming pattern similar to how `feature_#_format` is used for new formats.  I think the existing branch naming pattern would also work for format edits, so maybe just think about whether the template is also good for both purposes (new vs edit).

**Comment by mbjones** [comment]
I think a simpler template could work, as the `formatId` can not be changed. Other metadata can be changed, but presumably shouldn't fundamentally alter the type definition. If a typo or other change in metadata is needed, that would be fine, and all we really need to know is what the new value is, and why it should be changed.

**Comment by mbjones** [comment]
I added a new template for a proposed set of changes to an existing format. Let me know how that looks @twhiteaker 

Regarding branch naming patterns, I think we can just use `feature_#_format` for this as well.

**Comment by twhiteaker** [comment]
Looks good. Just remove the extra space between mediaType and the colon.
