### ISSUE TITLE
change ncml media type

### ISSUE THREAD

**Issue by twhiteaker** [DataONEorg/object-formats#8]
For formatId http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2, do you have examples where NCML files have a .nc extension (indicating a netCDF binary file)?  I thought NCML files typically had a .ncml extension.  They're just XML files, so I suppose they could also have a .xml extension.  Hmmm, I just thought of another question: Do you allow multiple media types or file extensions, such as .tiff and .tif?

**Comment by mbjones** [comment]
I'm not sure where that came from. I agree NCML files are more likely to have `.xml` or `.ncml` extensions. 

The [ObjectFormat `extension` field](https://dataone-architecture-documentation.readthedocs.io/en/latest/apis/Types2.html#v2_0.Types.ObjectFormat) is not repeatable. It is defined as "Suggested file name extension to be used when serializing this type of object to a file. The value should not include the period (.)." So it is really meant to be the preferred extension, and not a comprehensive list. In DataONE, the main thing we use this for is to provide a filename extension when serializing files for which the user didn't provide a filename with extension in the [SystemMetadata](https://dataone-architecture-documentation.readthedocs.io/en/latest/apis/Types2.html#v2_0.Types.SystemMetadata).

**Comment by twhiteaker** [comment]
I started a PR #11 on branch feature_8_ncml that updates NCML's media type and extension. The media type is from:

https://docs.opengeospatial.org/is/14-100r2/14-100r2.html

The document states:

> MIME type string used to refer to ncML-G dataset encoding is: `application/ncML+xml`. This xml media type is still unregistered.

I checked IANA and that type is still unregistered, but the pattern seems fine so I went with it.

**Comment by mbjones** [comment]
Your changes look good to me @twhiteaker. Let's give it a bit for others to have a chance to review and comment, but it seems non-controversial to me.

**Comment by mbjones** [comment]
No comments objected to this change, so I merged into `develop` for release with 1.23.
